### ISSUE TITLE
[!] Unable to find a specification for `AirMapSDK.podspec`

### ISSUE THREAD

**Issue by mdonahoe** [airmap/AirMapSDK-Swift#1]
I just cloned this repo and was unable to try the Example:

> git clone git@github.com:airmap/AirMapSDK-Swift.git
> cd AirMapSDK-Swift/
> brew install ruby
> sudo gem install cocoapods
> pod try AirMapSDK.podspec

[!] Unable to find a specification for `AirMapSDK.podspec`

I'm new to cocoapods, so it is probably something minor I haven't configured yet.

**Comment by f2m2rd** [comment]
Hi @mdonahoe, 

You don't need to clone it the repo. 

First install [cocapods](http://cocoapods.org):
`sudo gem install cocoapods`

If you want to try the SDK, then run:
'pod try AirMapSDK`

Also, make sure you sign up for an [AirMap Developer Account](http://developers.airmap.com) and download a config file.

Check out the getting started guide:  
https://developers.airmap.com/v2.0/docs/ios-getting-started

And reach out if you ned anything!

Cheers.
