### ISSUE TITLE
Swift Compiler Errors

### ISSUE THREAD

**Issue by Neilfau** [airmap/AirMapSDK-Swift#10]
Ive installed the AirMapSDK using cocoapods but when i open my workspace & try to build the project I get 59 swift compile errors. This a new project and made sure I set **Use Legacy Swift Language** is set to **YES**. Any other ideas how I can fix theses errors?

**Comment by f2m2rd** [comment]
Hi @Neilfau, 

You have a couple of options depending on which version of Swift you want to use for your application: 


##  Swift 2.3

If want to build your project on Swift 2.3, you will need to set the build configuration for each pod target to use SWIFT_VERSION 2.3.   You can do this by adding the following statement the end of your Podfile and then run `pod install`:

`post_install do |installer|
	installer.pods_project.targets.each do |target|
		target.build_configurations.each do |config|
			config.build_settings['SWIFT_VERSION'] = '2.3'
		end
	end
end`

##  Swift 3.0

We are nearing a release an Swift 3 version of the `AirMapSDK-Swift`.  If you would like to try this version, then update your Podfile with the following:

`pod 'AirMapSDK', :git => 'https://github.com/airmap/AirMapSDK-Swift.git', :branch => 'develop'`

Please let us know you have any other issues.

**Comment by Neilfau** [comment]
Ok thanks!

 Ill try out the Swift 3.0 version.
