### ISSUE TITLE
AirMapStatus

### ISSUE THREAD

**Issue by Neilfau** [airmap/AirMapSDK-Swift#12]
Hi, 

Im trying to get the flight status for a single point. When I use the following code 

`let coordinate = CLLocationCoordinate2D(latitude: 34.0168106, longitude: -118.4972862)
        
        AirMap.checkCoordinate(coordinate: coordinate, buffer:1000) { (status) in
            
            print("Airmap Status: \(status)")
            
           
            
        }
`

I get AirMap.AirMapStatus object returned but Im not finding a way to get any useable information out of it, Ive tried looking through the docs but can't find anything or any examples how to use this.

Any pointers would be greatly appreciated!

**Comment by f2m2rd** [comment]
Ah yes, you are using a version of our SDK that is still in development, so we haven't documented this yet.  Here is an example of how to get an error or value:

```
AirMap.checkCoordinate(coordinate: coordinate, buffer:1000) { status in

switch status {
case .error(let error):
AirMap.logger.error(error)
case .value(let advisories):
AirMap.logger(advisories)
}
}
```

**Comment by Neilfau** [comment]
Im still getting a AirMap.AirMapStatus object printed out even when I use that switch argument.

**Comment by f2m2rd** [comment]
Hi @Neilfau - The AirMapStatus is an object with different properties that you can access. 

The example below prints out some of those properties that should be useful, as well as opens a convenient UI with a list of the advisories by calling `showAdvisoryViewController` with the AirMapStatus object. 

```
AirMap.logger.minLevel = .debug
let coordinate = CLLocationCoordinate2D(latitude: 34.016815, longitude: -118.4972862)
AirMap.checkCoordinate(coordinate: coordinate, buffer: 1000, completion: { result in
	
	switch result {
		
	case .error(let error):
		AirMap.logger.error(error)
	case .value(let status):
		
		// Logging
		
		AirMap.logger.debug("advisoryColor: \(status.advisoryColor.rawValue)")
		AirMap.logger.debug("maxSafeDistance: \(status.maxSafeDistance)")
		
		AirMap.logger.debug("-------------- Start Advisories List -------------- ")
		
		for advisory in status.advisories {
			AirMap.logger.debug(advisory.name)
		}
		
		AirMap.logger.debug("-------------- End Advisories List-------------- ")
		
		// Display this list of Advisories in a UI
		self.showAdvisoryViewController(status: status)
		break
	}
})
```

```
func showAdvisoryViewController(status: AirMapStatus){
	
	if let advisoriesViewController = AirMap.statusAdvisoriesViewController(status, delegate: nil) {
		self.present(advisoriesViewController, animated: true, completion: nil)
	}
}
```

**Comment by Neilfau** [comment]
Ok thanks for the help, Ill have a look. Is there any docs showing the swift API references?

**Comment by f2m2rd** [comment]
Here is a link to our [documentation](https://developers.airmap.com/docs/ios-getting-started):
https://developers.airmap.com/docs/ios-getting-started

The documentation will be updated when we release the Swift 3 update to AirMapSDK-Swift.

**Comment by Neilfau** [comment]
I mean reference documentation outlining different methods, classes, constants available etc?
