### ISSUE TITLE
Adding Objective-C support would break the SDK?

### ISSUE THREAD

**Issue by jgrantr** [airmap/AirMapSDK-Swift#14]
Per the comment left on #13 it sounds like there is some issue with adding Objective-C support that is somehow not obvious or not caught by the compiler.

I would like a few more details, as the changes I made in that pull request compile cleanly and runs without errors.  It simply has classes that are currently not inheriting from any object instead inherit from NSObject (thereby exposing them into the Objective-C runtime).  Our company is looking to transition from the JS version of AirMap to the native version.  Our codebase is Objective-C, and we are not looking to add a bunch of Swift code (that we have to maintain) to the mix.  If there is an issue, we would love to help find a solution.  We also don't want to maintain our own version of the AirMap SDK long-term, so it would be great if we could find a resolution to this.

Thanks!

**Comment by f2m2rd** [comment]
We removed NSObject dependencies in order to support other use cases for this SDK (i.e Linux).

What aspects of the SDK are you using?

**Comment by jgrantr** [comment]
We are using the 'checkCoordinate' function (and the classes that stem off AirMapStatus) to check the airspace.  We are also using the AirMapMapView and the associated information contained in the various layers.  I'm not sure how much of that is from AirMap and how much is from MapBox, but we are detecting taps on the various areas on the maps and then displaying information from the underlying features by calling the 'visibleFeaturesAtPoint' function which ultimately comes from the MGLMapView.  These overlays appear to have happened automagically with the JS version but does not appear to do so with the native iOS version.

**Comment by f2m2rd** [comment]
Are you using the checkCoordinate for just weather and advisory color?  If so, we can create a bridgeable Swift wrapper for you to use in your application.

**Comment by jgrantr** [comment]
So, if the use case was Linux, why not use something like this:

Create a base class that objects that COULD be exposed to Objective-C would inherit from. The implementation would look like this:

#if os(Linux)
open class AirMapBaseClass { }
#else
open class AirMapBaseClass: NSObject { }
#endif

This would still allow you to maintain Linux compatibility and would also allow easy interoperability with Objective-C.  I could make those changes and alter my patch if that is an acceptable alternative.

**Comment by f2m2rd** [comment]
Hi @jgrantr - I'll discuss this option with the team and get back with you.
