### ISSUE TITLE
Traffic Not Working

### ISSUE THREAD

**Issue by Neilfau** [airmap/AirMapSDK-Swift#15]
In the docs it say you can enable real time traffic alerts by adding:

`AirMap.trafficDelegate = self`

and implementing the protocol methods.

Ive done this but nothing is happening, I'm not even getting a print message from 
`func airMapTrafficServiceDidConnect() {
		print("Connected")
	}
 `

Is there something I'm missing?

**Comment by f2m2rd** [comment]
Traffic will only work during an active Flight.  Are you creating a Flight first?  What's your workflow?

If you run a pod try AirMapSDK, you can run the example app after you've added the airmap.config.json to the project.  The example app includes creating a Flight and receiving Traffic.

**Comment by Neilfau** [comment]
Ah ok, think thats my problem, didn't create an Active Flight first.

Thanks!

**Comment by f2m2rd** [comment]
Great, let us know if you need anything else!
