### ISSUE TITLE
Flickering map.

### ISSUE THREAD

**Issue by nab0y4enko** [airmap/AirMapSDK-Swift#20]
The last update added a serious error: the map flashes many times after the first download.
This is perfectly visible, even in your example.
We receive a lot of angry messages from users.

[Screen record](https://monosnap.com/file/735UNxOMy3FxD9esKrx0rLwyzTJ7qC)

**Comment by f2m2rd** [comment]
@nab0y4enko 

We have identified the issue, which is an issue with MapBox, and have opened up a issue in the MapBox GL Native GitHub repo:

[https://github.com/mapbox/mapbox-gl-native/issues/10049]()

**Comment by nab0y4enko** [comment]
Hello, @f2m2rd.
Our team found out that the flicker appears when the TFR (Temponary Flight Restriction) layer is turned on.
I hope this information will help you in fixing problems.

**Comment by f2m2rd** [comment]
Yes, we let your team know what the issue was and It’s now resolved.
https://github.com/mapbox/mapbox-gl-native/issues/10049
