### ISSUE TITLE
Rulesets example "AirMapSDK WARNING: Map must complete initialization before configuring with rulesets"

### ISSUE THREAD

**Issue by nab0y4enko** [airmap/AirMapSDK-Swift#26]
We are trying to upgrade to the new version of the SDK. But the example in the rulesets branch does not work. The map does not load, and in the log we see only one error. 

![airmap config json e2 80 94 edited 2017-11-22 20-15-49](https://user-images.githubusercontent.com/1070269/33143571-f5c32122-cfc2-11e7-9609-3cafe56eb0bd.png)
![iphone 8 plus - ios 11 1 2017-11-22 20-17-54](https://user-images.githubusercontent.com/1070269/33143572-f5e16efc-cfc2-11e7-94a8-efa28790f574.png)
Please check your Example.

**Comment by f2m2rd** [comment]
@nab0y4enko the new SDK isn't ready for production at this time.  We will update the readme when it is ready.
