### ISSUE TITLE
Following the setup instructions for the example app result in several errors

### ISSUE THREAD

**Issue by avdwerff** [airmap/AirMapSDK-Swift#27]
I followed the instructions for the example app as described on https://developers.airmap.com/v2.1/docs/getting-started-ios 

Compiling the app gives me a lot of errors: 
$' is not an identifier; use backticks to escape it Replace '$' with '`$`'
and
No such module 'libPhoneNumber_iOS'

**Comment by adolfo** [comment]
Closing; see #28
