### ISSUE TITLE
iOS 11, XCode 9.3.1 And Swift4 compile issues

### ISSUE THREAD

**Issue by ahimanshuios11** [airmap/AirMapSDK-Swift#31]
Dear Team,

I am an iOS Application developer. I am using your AirkMapSDK-Swift in my project.

As we know that iOS application must require to support iOS 11 from July 1st. For the same I am just updated my XCode version 8.3.3 to XCode version 9.3.1. I am getting a lot of issues in your AirkMapSDK-Swift and even I tried to use your beta version 2.0.0 Beta 3 so that I am able to compile my code but could not got success in it. So I am seeking your attention on my this concern ASAP.

I attached my issues screen-shot. Kindly look into it and provide your assistance to us. 

I am very grateful to you.

Thanks
Himanshu A
<img width="1228" alt="xcode9 3 1-airmapsdk-issues" src="https://user-images.githubusercontent.com/39907013/40914186-d47e6766-6814-11e8-9cad-f5a08d3679be.png">

**Comment by adolfo** [comment]
Hi @ahimanshuios11. Please downgrade your Mapbox to < 4.0. We don't currently support the latest release as not all functionality we need has been implemented. Please add the following to your Podfile
```
pod 'Mapbox-iOS-SDK', '< 4.0'
```
Or you can use the latest commit from master which already has this fix applied
```
pod 'AirMapSDK', :git => 'https://github.com/airmap/AirMapSDK-Swift', :branch => 'master'
```

**Comment by ahimanshuios11** [comment]
Thanks @adolfo . 
Yes now we are able to compile our app. Thank you so much for your quick response.
