### ISSUE TITLE
AirMapSDK DEBUG: Unknown airspace type non_geo, AirMapSDK DEBUG: Unknown airspace type laanc

### ISSUE THREAD

**Issue by ahimanshuios11** [airmap/AirMapSDK-Swift#33]
Dear Team,

Recently I updated my AirMapSDK from version 1.0.3 to your latest beta veriosn 2.0.0.beta.4. So that I can able to upload my app to AppStore with iOS 11 support.

After updating to XCode 9.3.1, I am able to compile my code with your support. Now I am facing some strange issue and I would like to seek your attention here. See details below:

We are using your SDK to configure our map in regards with "TFRs", "WILDFIRES" layers. Previously we are using below code segment for the same:
  ```
private let mapLayers: [AirMapLayerType] = [.tfrs, .wildfires]
    private let mapTheme: AirMapMapTheme = .standard
   self.airMapView.configure = (layers: self.mapLayers, theme: self.mapTheme) 
```

As latest AirMapSDK provide this by some changes in APIs so now I am using below source code for getting the same objective as above:

```
// set the visual style
                self.airMapView.theme = .light
// alternatively, the map can be configured with a list preferred ruleset ids 
                self.airMapView.rulesetConfiguration = .dynamic(preferredRulesetIds: ["usa_sec_91"], enableRecommendedRulesets: false)
```

OR

I have tried below lines of code as well but getting the same issue.
```
// set the visual style
                self.airMapView.theme = .light
self.airMapView.rulesetConfiguration = .automatic
```

We are getting below message on our console prior to getting app crash. See attachment as well.
<img width="1207" alt="airmapsdk-swift-ios11-crash" src="https://user-images.githubusercontent.com/39907013/41229943-89050cd6-6d9b-11e8-9591-e72488a76e5a.png">

> AirMapSDK DEBUG: Unknown airspace type non_geo
> AirMapSDK DEBUG: Unknown airspace type non_geo
> AirMapSDK DEBUG: Unknown airspace type non_geo
> AirMapSDK DEBUG: Unknown airspace type laanc
> AirMapSDK DEBUG: Unknown airspace type non_geo
> AirMapSDK DEBUG: Unknown airspace type non_geo
> AirMapSDK DEBUG: Unknown airspace type non_geo
> AirMapSDK DEBUG: Unknown airspace type non_geo
> AirMapSDK DEBUG: Unknown airspace type laanc
> AirMapSDK DEBUG: Unknown airspace type non_geo
> AirMapSDK DEBUG: Unknown airspace type non_geo
> AirMapSDK DEBUG: Unknown airspace type non_geo
> AirMapSDK DEBUG: Unknown airspace type non_geo
> AirMapSDK DEBUG: Unknown airspace type laanc
> AirMapSDK DEBUG: Unknown airspace type non_geo
> AirMapSDK DEBUG: Unknown airspace type non_geo
> AirMapSDK DEBUG: Unknown airspace type non_geo
> AirMapSDK DEBUG: Unknown airspace type non_geo
> AirMapSDK DEBUG: Unknown airspace type laanc
> AirMapSDK DEBUG: Unknown airspace type non_geo

I hope you understand my concerns well from above details. Do you need any further details on it, I am happy to provide it to you.

I am looking forward for your kind attention here. Kindly provide your needful inputs/assistance ASAP so that I am able to release my app along with this feature. I am very grateful to you.

**Comment by adolfo** [comment]
@ahimanshuios11 please test with latest commits on `master` and see if you are able to reproduce the crash there. 

```pod 'AirMapSDK', :git => 'https://github.com/airmap/AirMapSDK-Swift', :branch => 'master'```

The following should be sufficient to display required airspace such as TFRs  and Wildfires
```
self.airMapView.rulesetConfiguration = .automatic
```
