### ISSUE TITLE
AirMapSDK rc1 build error

### ISSUE THREAD

**Issue by alcrus** [airmap/AirMapSDK-Swift#34]
pod 'AirMapSDK', :git => 'https://github.com/airmap/AirMapSDK-Swift', :tag => '2.0.0.rc.1'

![image](https://user-images.githubusercontent.com/1839567/41815627-b25f1048-7725-11e8-818d-86201473b259.png)

Anybody test it before pushing to master and writing documentation? Is it ever normal to commit unfinished code directly to master?

**Comment by adolfo** [comment]
Hi @alcrus. My apologies – looks like the Cocoapods version broke from a Carthage fix. This should be resolved by 9ef5d0492a640f3241b2959780d2ac4428a3d49d. Please run the following:
```
pod cache clean AirMapSDK && pod update AirMapSDK
```

**Comment by alcrus** [comment]
Thank you for the fix! Works now.
