### ISSUE TITLE
RxSwift reentrancy anomaly

### ISSUE THREAD

**Issue by alcrus** [airmap/AirMapSDK-Swift#35]
There is RxSwift reentrancy anomaly when resolve rulesets in advanced map demo. Any ideas or recommendations how to fix that are really appreciated. Is it expected? The problem is map doesn't show advisories when becomes visible (you have to move it after app start to show advisories), probably because of that. Thanks.

```swift
activeRulesets = AirMapRulesetResolver.resolvedActiveRulesets(
    with: Array(preferredRulesetIds),
    from: jurisdictions,
    enableRecommendedRulesets: false)
```

Reentrancy anomaly was detected.
  > Debugging: To debug this issue you can set a breakpoint in /Users/alzhilin/Src/gopilot/Pods/RxSwift/RxSwift/Rx.swift:97 and observe the call stack.
  > Problem: This behavior is breaking the observable sequence grammar. `next (error | completed)?`
    This behavior breaks the grammar because there is overlapping between sequence events.
    Observable sequence is trying to send an event before sending of previous event has finished.
  > Interpretation: This could mean that there is some kind of unexpected cyclic dependency in your code,
    or that the system is not behaving in the expected way.
  > Remedy: If this is the expected behavior this message can be suppressed by adding `.observeOn(MainScheduler.asyncInstance)`
    or by enqueing sequence events in some other way.

**Comment by f2m2rd** [comment]
This issue has been resolved in the latest release 2.0.1
