### ISSUE TITLE
AirMapMapView not properly deiniting

### ISSUE THREAD

**Issue by justinmiller62** [airmap/AirMapSDK-Swift#56]
The mapview doesn't appear to properly deinit and the memory does not get cleaned up. I noticed when you create a map and then nil the map out and deinit the view controller the map stays persistent in memory and will keep climbing each time that map is initialized. Using the latest version.

**Comment by Michael-AirMap** [comment]
Fixed in [#70](https://github.com/airmap/AirMapSDK-Swift/pull/70)
