### ISSUE TITLE
Build error Xcode 10.2

### ISSUE THREAD

**Issue by alcrus** [airmap/AirMapSDK-Swift#71]
AirMapSDK-Swift 3.0.0.beta.1

Pods/AirMapSDK/Source/UI/AirMapFlightAnnotation.swift:40:20:
'NSObject.hashValue' is not overridable; did you mean to override 'NSObject.hash'?

**Comment by Michael-AirMap** [comment]
Hi @alcrus thank you for brining this to our attention. We will resolve this soon

**Comment by nab0y4enko** [comment]
@Michael-AirMap Do you plan add supporting for Xcode 10.2?

**Comment by Michael-AirMap** [comment]
@nab0y4enko Yes. I am working to get a release out
